// GoogleLogin.js
import React from 'react';

const GoogleLogin = () => {
    const handleLogin = () => {
        // This URL is generated by django-allauth
        // It triggers the OAuth flow and eventually redirects back to LOGIN_REDIRECT_URL
        window.location.href = 'http://127.0.0.1:8000/accounts/google/login/';
    };

    return (
        <div className="login-page" style={{ textAlign: 'center', marginTop: '100px' }}>
            <h1>F1 Telemetry Dashboard</h1>
            <p>Please sign in with Google to view driver data.</p>
            <button
                onClick={handleLogin}
                style={{
                    padding: '10px 20px',
                    backgroundColor: '#4285F4',
                    color: 'white',
                    border: 'none',
                    borderRadius: '5px',
                    cursor: 'pointer',
                    fontSize: '16px'
                }}
            >
                Sign in with Google
            </button>
        </div>
    );
};

export default GoogleLogin;